### PR TITLE
Added full JSON

### PR DESCRIPTION
**Pull request by cephalin**

### CODE REVIEW

**Comment by cephalin** [comment]
An additional commit to update the AadPicker code to the same as [here](https://github.com/Azure-Samples/active-directory-dotnet-webapp-groupclaims/blob/master/WebApp-GroupClaims-DotNet/Scripts/AadPickerLibrary.js). Hope that's ok.

**Comment by dstrockis** [comment]
What is the AadPicker even used for in this sample? I thought I took it out of the UI, but it looks like I left the script itself in there.  We should just delete it.

**Comment by cephalin** [comment]
I use  it in my tutorial. If you take it out then I would have to use a different sample for my tutorial, but I’d rather use this one.

**Comment by dstrockis** [comment]
Can you share a link for your sample?

**Comment by cephalin** [comment]
https://azure.microsoft.com/en-us/documentation/articles/web-sites-dotnet-lob-application-azure-ad

**Comment by jmprieur** [comment]
I've added the full json for the single-tenant case.

**Pull request closed without merging**
